# tools/gen-pinyin.ps1  (keep this file pure ASCII: PS 5.1 reads no-BOM files as GBK)
# Generate src/pinyin_data.cpp from pinyin-data.txt (mozillazg/pinyin-data, MIT).
# Data format: one line per codepoint:  U+4E00: yi  # comment
# Only keeps U+4E00..U+9FFF (the range toPinyin converts); tone marks are
# stripped so the output matches the ICU "Latin-ASCII" behavior.
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$inFile  = Join-Path $root 'tools\pinyin-data.txt'
$outFile = Join-Path $root 'src\pinyin_data.cpp'

if (-not (Test-Path $inFile)) {
    throw "missing $inFile (download from https://github.com/mozillazg/pinyin-data)"
}

$lines = [System.IO.File]::ReadAllLines($inFile, [System.Text.Encoding]::UTF8)
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// pinyin_data.cpp - AUTO-GENERATED by tools/gen-pinyin.ps1, do not edit by hand.')
[void]$sb.AppendLine('// Source: mozillazg/pinyin-data (MIT), readings from Unicode Unihan kMandarin.')
[void]$sb.AppendLine('// Copyright (c) 2016 mozillazg - https://github.com/mozillazg/pinyin-data')
[void]$sb.AppendLine('#include "pinyin.h"')
[void]$sb.AppendLine('#include <cstdint>')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('struct PinyinEntry { uint32_t cp; const char *py; };')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('static const PinyinEntry kPinyinTable[] = {')

$count = 0
$prev = 0
foreach ($ln in $lines) {
    if (-not $ln.StartsWith('U+')) { continue }
    $m = [regex]::Match($ln, '^U\+([0-9A-Fa-f]{4,5}):\s*([^\s#]+)')
    if (-not $m.Success) { continue }
    $cp = [Convert]::ToInt32($m.Groups[1].Value, 16)
    if ($cp -lt 0x4E00 -or $cp -gt 0x9FFF) { continue }
    if ($cp -le $prev) { throw "pinyin-data.txt not sorted at: $ln" }
    $prev = $cp
    $py = $m.Groups[2].Value
    # multi-reading entries are comma-separated ("du,duo,zhai"): keep only the
    # first (most common) reading, same as ICU single-char conversion
    $comma = $py.IndexOf(',')
    if ($comma -ge 0) { $py = $py.Substring(0, $comma) }
    # strip tone marks via codepoint map; u-umlaut family maps to u (ICU Latin-ASCII)
    $map = @{
        0x0101='a'; 0x00E1='a'; 0x01CE='a'; 0x00E0='a'
        0x0113='e'; 0x00E9='e'; 0x011B='e'; 0x00E8='e'; 0x00EA='e'
        0x012B='i'; 0x00ED='i'; 0x01D0='i'; 0x00EC='i'
        0x014D='o'; 0x00F3='o'; 0x01D2='o'; 0x00F2='o'
        0x016B='u'; 0x00FA='u'; 0x01D4='u'; 0x00F9='u'
        0x00FC='u'; 0x01D6='u'; 0x01D8='u'; 0x01DA='u'; 0x01DC='u'
        0x0144='n'; 0x0148='n'; 0x01F9='n'
        0x1E3F='m'
    }
    $chars = $py.ToCharArray()
    for ($i = 0; $i -lt $chars.Length; $i++) {
        $k = [int]$chars[$i]
        if ($map.ContainsKey($k)) { $chars[$i] = [char]$map[$k] }
    }
    $py = -join $chars
    # drop anything left (apostrophes, combining marks, stray chars)
    $py = $py -replace '[^a-z]', ''
    if ($py.Length -eq 0) { continue }
    $hex = $cp.ToString('X4')
    [void]$sb.AppendLine('    {0x' + $hex + ', "' + $py + '"},')
    $count = $count + 1
}
[void]$sb.AppendLine('};')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('const char *pinyinLookup(uint32_t cp)')
[void]$sb.AppendLine('{')
[void]$sb.AppendLine('    int lo = 0;')
[void]$sb.AppendLine('    int hi = int(sizeof(kPinyinTable) / sizeof(kPinyinTable[0])) - 1;')
[void]$sb.AppendLine('    while (lo <= hi) {')
[void]$sb.AppendLine('        const int mid = (lo + hi) / 2;')
[void]$sb.AppendLine('        const uint32_t v = kPinyinTable[mid].cp;')
[void]$sb.AppendLine('        if (v == cp) return kPinyinTable[mid].py;')
[void]$sb.AppendLine('        if (v < cp) lo = mid + 1; else hi = mid - 1;')
[void]$sb.AppendLine('    }')
[void]$sb.AppendLine('    return nullptr;')
[void]$sb.AppendLine('}')
[System.IO.File]::WriteAllText($outFile, $sb.ToString(), [System.Text.Encoding]::ASCII)
Write-Output ("entries: " + $count)
Write-Output ("bytes: " + (Get-Item $outFile).Length)
